### ISSUE TITLE
Also run regular linters when running --fix

### ISSUE THREAD

**Issue by neob91-close** [closeio/lintlizard#142]
I often find myself having to run `lintlizard --fix`, and then `lintlizard` again without the flag to see if there's anything else that needs manual fixing. It would be convenient if `lintlizard --fix` could also run non-fixable linters.

@vtclose @AlecRosenbaum

**Comment by vtclose** [comment]
`--fix-and-check`? I think this might be useful as a pre-commit hook (cc @nsaje)
